"""Add task_id to sync_logs

Revision ID: b3d15f04c640
Revises: 58b89e140d00
Create Date: 2026-02-21 19:58:45.273494

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b3d15f04c640"
down_revision: Union[str, Sequence[str], None] = "58b89e140d00"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sync_logs", sa.Column("task_id", sa.UUID(), nullable=True))
    op.create_foreign_key(None, "sync_logs", "automation_tasks", ["task_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "sync_logs", type_="foreignkey")  # type: ignore
    op.drop_column("sync_logs", "task_id")
    # ### end Alembic commands ###
