"""add user_credentials and global_settings tables

Revision ID: b85f41ed1fb8
Revises: 2a3b4c5d6e7f
Create Date: 2026-05-22 12:33:10.826392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b85f41ed1fb8'
down_revision: Union[str, Sequence[str], None] = '2a3b4c5d6e7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fiorilli_url', sa.String(), nullable=False),
    sa.Column('fiorilli_user', sa.String(), nullable=False),
    sa.Column('ahgora_url', sa.String(), nullable=False),
    sa.Column('ahgora_user', sa.String(), nullable=False),
    sa.Column('ahgora_company', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_credentials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('fiorilli_url', sa.String(), nullable=True),
    sa.Column('fiorilli_user', sa.String(), nullable=True),
    sa.Column('fiorilli_password_encrypted', sa.String(), nullable=True),
    sa.Column('ahgora_url', sa.String(), nullable=True),
    sa.Column('ahgora_user', sa.String(), nullable=True),
    sa.Column('ahgora_password_encrypted', sa.String(), nullable=True),
    sa.Column('ahgora_company', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_credentials')
    op.drop_table('global_settings')
    # ### end Alembic commands ###
