"""add_retry_fields

Revision ID: caaf8a54d58f
Revises: 96e58f4e027c
Create Date: 2026-02-19 12:41:50.101017

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "caaf8a54d58f"
down_revision: Union[str, Sequence[str], None] = "96e58f4e027c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add columns as nullable first
    op.add_column("sync_jobs", sa.Column("retry_count", sa.Integer(), nullable=True))
    op.add_column("sync_jobs", sa.Column("next_retry_at", sa.DateTime(), nullable=True))

    # Update existing rows
    op.execute("UPDATE sync_jobs SET retry_count = 0 WHERE retry_count IS NULL")

    # Make retry_count NOT NULL
    op.alter_column("sync_jobs", "retry_count", nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sync_jobs", "next_retry_at")
    op.drop_column("sync_jobs", "retry_count")
    # ### end Alembic commands ###
